### ISSUE TITLE
Comment the license header

### ISSUE THREAD

**Issue by lord63** [lord63/licen#2]
Currently, I didn't do it.
Here are my reasons:
- Your IDE or editor can easily do it.
- There are many languages and different comment syntaxes. How many languages should I support or just support all I knows?
- I don't use it :p

maybe we can add a `-c --comment` argument. 
Let me know your ideas :)

**Comment by lbeltrame** [comment]
`--comment` sounds the most logical idea.

**Comment by bestony** [comment]
check the `.gitattribute` file to determine use which style.

https://github.com/alexkaratarakis/gitattributes

**Comment by lord63** [comment]
Keep it simple and stupid, closed.
