### ISSUE TITLE
Support "or later" variants for [L]GPL licenses

### ISSUE THREAD

**Issue by lbeltrame** [lord63/licen#4]
For [L]GPL'd software, there's always the option of using either the version "as is", or include the wording "or (at your option) any later version". This is important for large projects, which may deem necessary either keep one license version, or be able to move freely to the next version.

**Comment by lord63** [comment]
I'm sorry, I don't understand what you said.
Something with the license template? I get all of them from http://choosealicense.com

**Comment by lbeltrame** [comment]
In data lunedì 23 marzo 2015 16:21:03, lord63 ha scritto:

> I'm sorry, I don't understand what you said.
> Something with the license template? I get all of them from

Yes, for example, from my own software (GPL 3):

-- snip --

  is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

-- snip --

The "at your option" is optional, but it makes quite a difference from a 
licensing point of view.

**Comment by lord63** [comment]
@lbeltrame 
Hi, I diffed your [license](https://github.com/lbeltrame/danbooru-client/blob/master/COPYING) with the template from [choosealicense](http://choosealicense.com/licenses/gpl-2.0/), it seems thats except the 'http://fsf.org/' link and some tiny difference, they are the same.
I still feel a bit puzzled, may be you can submit a pull request :)

**Comment by lbeltrame** [comment]
In data mercoledì 25 marzo 2015 06:36:12, lord63 ha scritto:

> thats except the 'http://fsf.org/' link and some tiny difference, they
> are the same. I still feel a bit puzzled, may be you can submit a pull
> request :)

The difference is only in "or later part":

For example, let's imagine a program licensed under GPL v2 "or later" (as 
written)
- if "or later" is there → I can license it as GPL v2, or v3, or whatever 
  comes out next, even if I'm not the original author (because the license 
  grants me this option)
- if there isn't → I can only use v2, anything else requires approval from the 
  original author (major example in the wild: the Linux kernel)

So what I'm suggesting is to have a text with "or...blablabla any later 
version" and one without it, and make options like "gplv3+" or "gplv3" and so 
on.

**Comment by lord63** [comment]
> This program is free software; you can redistribute it and/or modify
>     it under the terms of the GNU General Public License as published by
>     the Free Software Foundation; either version 2 of the License, or
>     (at your option) any later version.

There is also a 'later part' in the template boilerplate notice from licen. Check [it](https://github.com/lord63/licen/blob/master/licen/templates/licenses/gpl-2.0#L296) out

> So what I'm suggesting is to have a text with "or...blablabla any later version" and one without it, and make options like "gplv3+" or "gplv3" and so on.

Do you mean two seperate license template?

---

All the license templates are come from choosealicense, I think we can rely on it. Any thoughts?

**Comment by lbeltrame** [comment]
In data venerd� 27 marzo 2015 20:03:31, lord63 ha scritto:
.

> Do you mean two seperate license template?

Exactly that.

**Comment by lord63** [comment]
I'm sorry, this may won't fix.
Currently I think one is enough, if you really want it, I'm afraid that you have to add your own template manually.
Thanks for you advice!
